server:
  port: 8089
spring:
  application:
    name: order-service
  datasource:
    #url: jdbc:mysql://localhost:3306/yun6?useUnicode=true&characterEncoding=UTF-8
    #username: root
    #password: root
    #druid相关配置
    druid:
      #监控统计拦截的filters
      filters: stat
      driver-class-name: com.mysql.cj.jdbc.Driver
      #基本属性
      url: jdbc:mysql://39.106.55.16:3306/leyou?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
      username: root
      password: root
      #配置初始化大小/最小/最大
      initial-size: 1
      min-idle: 1
      max-active: 20
      #获取连接等待超时时间
      max-wait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      #一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
  jackson:
    default-property-inclusion: non_null
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.leyou.order.pojo
ly:
  jwt:
    pubKeyPath: D:\software\rsa\rsa.pub  #公钥地址
    cookieName: LY_TOKEN
  worker:
    workerId: 1
    dataCenterId: 1