server:
  port: 8084
spring:
  application:
    name: page-service
  thymeleaf:
    cache: false
  main:
    allow-bean-definition-overriding: true
  rabbitmq:
    host: 192.168.150.128
    username: leetgou
    password: root
    virtual-host: /leetgou
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka